### ISSUE TITLE
error

### ISSUE THREAD

**Issue by madhuridhangar** [codejamninja/react-gantt#26]
< ReactGantt
      ^

SyntaxError: Unexpected token '<'
?[90m    at Loader.moduleStrategy (internal/modules/esm/translators.js:122:18)?[
39m
?[90m    at async link (internal/modules/esm/module_job.js:42:21)?[39m

**Comment by codejamninja** [comment]
Can you send me what you are doing that causes this issue?

**Comment by madhuridhangar** [comment]
I want to create a process scheduling algorithm simulator thats why i want to create ganttchart using react.js library.
And for that I'm using this given codes:
import ReactGantt, { GanttRow } from 'react-gantt';

class Demo extends Component {
  render() {
    return (
      <ReactGantt
        templates={{
          myTasks: {
            title: 'My Tasks',
            steps: [
              {
                name: 'Task Phase One',
                color: '#0099FF'
              },
              {
                name: 'Task Phase Two',
                color: '#FF9900'
              }
            ]
          }
        }}
        leftBound={moment().set({hour: 0, date: 30, month: 5, year: 2016}).toDate()}
        rightBound={moment().set({hour: 0, date: 29, month: 8, year: 2016}).toDate()}
      >
        <GanttRow
          title="Task 1"
          templateName="myTasks"
          steps={[
            moment().set({hour: 0, date: 1, month: 6, year: 2016}).toDate(),
            moment().set({hour: 0, date: 4, month: 8, year: 2016}).toDate(),
            moment().set({hour: 0, date: 17, month: 8, year: 2016}).toDate()
          ]}
        />
        <GanttRow
          title="Task 1"
          templateName="myTasks"
          steps={[
            moment().set({hour: 0, date: 27, month: 2, year: 2016}).toDate(),
            moment().set({hour: 0, date: 9, month: 7, year: 2016}).toDate(),
            moment().set({hour: 0, date: 22, month: 7, year: 2016}).toDate()
          ]}
        />
      </ReactGantt>
    );
  }
}


Can you suggest me some ways to creating simulator for scheduling algoritm's Gantt charts?
